### ISSUE TITLE
[Migration] Upload benchmark results to GCS

### ISSUE THREAD

**Issue by pzread** [openxla/openxla-benchmark#20]
The benchmark IDs and formats from the comparative benchmark suite is slightly different from the [iree-samples](https://github.com/iree-org/iree-samples). We need to backfill in the dashboard before uploading results to `gs://comparative-benchmark-artifacts`

**Comment by mariecwhite** [comment]
@reichlfl had some ideas on how to organize the artifacts in gcs.

**Comment by reichlfl** [comment]
> @reichlfl had some ideas on how to organize the artifacts in gcs.

Sorry, this comment slipped through the cracks. I was referring to the input definitions, not the artifact storage of results.
